apiVersion: v1
kind: Service
metadata:
  name: neutron-service
  namespace: neutron
  labels:
    name: neutron
    app: neutron
spec:
  type: ClusterIP
  ports:
  - name: port
    port: 9696
    targetPort: 9696
    protocol: TCP
  selector:
    app: neutron
