apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx
    name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: port
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx