name: build and push images
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: ["alpine", "nginx"]      
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}           
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker/${{ matrix.target }}
          provenance: false
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/${{ matrix.target }}:latest
            ghcr.io/${{ env.REPO }}/${{ matrix.target }}:${{ github.sha }}