name: build and push images
on:
  push:

env:
  ALPINE: alpine

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}     
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker/alpine
          provenance: false
          push: true
          tags: |
            ghcr.io/"${OWNER,,}"/${{ github.event.repository.name }}/${{ env.ALPINE }}:latest
            ghcr.io/"${OWNER,,}"/${{ github.event.repository.name }}/${{ env.ALPINE }}:${{ github.sha }}
        env:
          OWNER: ${{ github.repository_owner }}